# Generated by Django 2.2.10 on 2021-12-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(verbose_name='Parameter a')),
                ('b', models.IntegerField(verbose_name='Parameter b')),
            ],
        ),
    ]
